hooks:
  commit-msg:
    - conventional-tools commitlint
  pre-push:
    - conventional-tools commitlint -l1
  prepare-commit-msg:
    - |
        # Commitgen
        if [ -z "${2}" ]; then
          echo "$(conventional-tools commitgen)$(cat ${1})" > ${1};
        fi
commit:
  scopes:
    # Project scopes go here
    # - api
